### ISSUE TITLE
It should ignore commented lines

### ISSUE THREAD

**Issue by damnjan** [laxa1986/gulp-angular-embed-templates#1]
When you comment out a line containing "templateUrl:" in a js file, the plugin still tries to find the template. Instead, it should just ignore it.

**Comment by laxa1986** [comment]
I's pretty tricky, because I need to build in JS syntax analyser in my plugin. It is not so siple as // symbols at line start
// this is comment
var a = "hello // ups, it's not a comment"
also there ara multi line comments and special /*@cc_on @*/ comments for IE

Does this behavior block you?

**Comment by damnjan** [comment]
For now I just change "templateUrl" to something else so it is not a huge problem, considering how useful your plugin is to me, so thanks anyway!

**Comment by laxa1986** [comment]
Close the issue because it has simple work around and almost unreal to implement
