### ISSUE TITLE
Allow to filter matches.

### ISSUE THREAD

**Issue by hworld** [laxa1986/gulp-angular-embed-templates#10]
Thanks for such an awesome lib! I've been wanting this for a while now. It's such a better way than template caching, imo.

I made a fork/branch for this issue and it seems to be working: https://github.com/gamejolt/gulp-angular-embed-templates/commit/babb88729aac48a81e4c2af40f22a3de701f3da3

Basically, an option to be able to filter the matches through a function. I didn't make a PR since I didn't have time to do test cases for it.

**Comment by laxa1986** [comment]
Hello. I spent this weekend analizing you request. Finally I released a new
version 2.1.0 with 3 ways how to skip embedding: whole file, concrete
template and one shortcut. You can find details on home page
https://www.npmjs.com/package/gulp-angular-embed-templates

Please write me in case of any issues with this new release.

2016-02-04 12:55 GMT+02:00 hworld <notifications@github.com>:

> Thanks for such an awesome lib! I've been wanting this for a while now.
> It's such a better way than template caching, imo.
>
> I made a fork/branch for this issue and it seems to be working: gamejolt@
> babb887
> <https://github.com/gamejolt/gulp-angular-embed-templates/commit/babb88729aac48a81e4c2af40f22a3de701f3da3>
>
> Basically, an option to be able to filter the matches through a function.
> I didn't make a PR since I didn't have time to do test cases for it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laxa1986/gulp-angular-embed-templates/issues/10>.
>



-- 
Чекулаев Алексей

**Comment by hworld** [comment]
Whoa, this is really great! Thanks so much, I'll be sure to upgrade.
