### ISSUE TITLE
templateUrl: string = `template.html` is invalid

### ISSUE THREAD

**Issue by varadero** [laxa1986/gulp-angular-embed-templates#11]
Hello,

I can't make this plugin to work. The problem is the Regex which requires the following form of templateUrl property - ```templateUrl: string = `template.html` ``` - which is not valid. TypeScript 1.7.5 can't transpile this to JavaScript with the following error:
```
error TS2304: Cannot find name 'string'.
```

Your tests could pass but they work on invalid .ts file. I think the : string =" part of your Regex is not needed. Otherwise, the following correct templateUrl usage is not detected and the pluging does not change the file at all:
```
@Component({
    selector: "my-component",
    templateUrl: "app/path/template.html",
    directives: [ROUTER_DIRECTIVES]
})
```
Could you transpile the following file from your tests ```https://github.com/laxa1986/gulp-angular-embed-templates/blob/master/test/cases/angular2-typescript/directive.js``` ?

**Comment by garethdn** [comment]
+1 Same issue here

**Comment by garethdn** [comment]
Any plans to update the the regex?

**Comment by laxa1986** [comment]
Guys, I'm very sorry for delay, I've got very hard workload on my work and
last two days I was sick with high temperature.
Anyway, I'll check it today and came to you with answer or patch.

2016-02-20 15:10 GMT+02:00 Gareth Nolan <notifications@github.com>:

> Any plans to update the the regex?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laxa1986/gulp-angular-embed-templates/issues/11#issuecomment-186592433>
> .
>



-- 
Чекулаев Алексей

**Comment by garethdn** [comment]
@laxa1986 No worries at all - I was just curious as to whether this was being considered for a fix or not. Thanks.

**Comment by laxa1986** [comment]
Ok, guys, I looked at the issue. And I need your help to solve it. Lets split the discussion on several threads:

1. [templateUrl: path] it works fine. Just tested on your example @varadero . Just need to keep sourceType empty or specify sourceType: js.

2. [templateUrl: string = `path`] I just checked. This syntax works fine when you're defining a class field, like this:
class Component extends Directive {
  restrict: string = "E";
  controller: Controller;
  controllerAs: string = "vm";
  templateUrl: string = "angular2-template.html";
}
so I provided a wrong example in documentation
@View({
    ...
    templateUrl: string = 'angular2-template.html'
})
My fault, sorry. I will fix it.

3. [templateUrl: path]. In version 2.1.x I did major change, that you can use one one syntax: templateUrl: path or templateUrl: string = path. Now I understand that it was also mistake. Oh.. I'm going to release two more versions right now: 2.1.3 with fix in doc and 2.2.0 to enable templateUrl: path processing for Angular 2.0

**Comment by garethdn** [comment]
So, running Angular2, it's correctly identifying the `templateUrl` and embedding the template but I'm getting template parse errors (unexpected closing tags). These errors do not occur when the templates are not inlined. I can't be more help that that really, i'm not sure why it's happening.

```
return gulp
    .src('app/**/*.ts')
    .pipe(embedTemplates({sourceType:'ts'}))
    .pipe(sourcemaps.init())
    .pipe(typescript(tscConfig.compilerOptions))
    .pipe(uglify({ mangle: false }))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest('dist'));
```

I tried removing the `uglify` but the problem persists.

**Comment by laxa1986** [comment]
You did your gulpfile.js config correct. Can you send me '
checkulaevalexey@gmail.com' initial template and after embedding.
When it is being embedding all spaces and comments removed from it with '
https://www.npmjs.com/package/minimize'. You can play with different
minimize options using parameter embedTemplates({minimize: {..}}), but
you'd better send me particular template and try to find the reason.

2016-02-22 14:00 GMT+02:00 Gareth Nolan <notifications@github.com>:

> So, running Angular2, it's correctly identifying the templateUrl and
> embedding the template but I'm getting template parse errors (unexpected
> closing tags). These errors do not occur when the templates are not
> inlined. I can't be more help that that really, i'm not sure why it's
> happening.
>
> return gulp
>     .src('app/**/*.ts')
>     .pipe(embedTemplates({sourceType:'ts'}))
>     .pipe(sourcemaps.init())
>     .pipe(typescript(tscConfig.compilerOptions))
>     .pipe(uglify({ mangle: false }))
>     .pipe(sourcemaps.write('.'))
>     .pipe(gulp.dest('dist'));
>
> I tried removing the uglify but the problem persists.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laxa1986/gulp-angular-embed-templates/issues/11#issuecomment-187143398>
> .
>



-- 
Чекулаев Алексей

**Comment by garethdn** [comment]
Thanks @laxa1986 . The following config works for me

```
.pipe(embedTemplates({
      sourceType:'ts',
      minimize: {
        empty: true,
        spare: true,
        quotes: true,
        dom: {
          lowerCaseAttributeNames: false,
          lowerCaseTags: false 
        }
      }
    }))
```
