### ISSUE TITLE
What about a grunt version ?

### ISSUE THREAD

**Issue by phiphou** [laxa1986/gulp-angular-embed-templates#14]
Really love your plugin, but I'm using grunt... for now, I use grunt-gulp to run this gulp task trough my grunt workflow, but it would be easier if I can use a true grunt version of gulp-angular-embed-templates, don't you think ? ;)

**Comment by laxa1986** [comment]
Hello. Sorry for long delay. I'm not going to support Grunt, sorry. The
reason quite simple: I never worked with grunt and last 3 months my carier
changed and now I very small amount of time to work with JS. Nevetheles:
I'm going to make two more major relases with several features requested by
other guys. Then (I hope) none major features will appear and you can make
Grunt version by yourself.

2016-03-15 16:53 GMT+02:00 Phiphou <notifications@github.com>:

> Really love your plugin, but I'm using grunt... for now, I use grunt-gulp
> to run this gulp task trough my grunt workflow, but it would be easier if I
> can use a true grunt version of gulp-angular-embed-templates, don't you
> think ? ;)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/laxa1986/gulp-angular-embed-templates/issues/14
>



-- 
Чекулаев Алексей

**Comment by phiphou** [comment]
It's really not a problem, was just asking ;) I switched my project to gulp, that was easy and did it quicly ;)
