### ISSUE TITLE
Stripping quotes from img src breaks image

### ISSUE THREAD

**Issue by skliffmueller** [laxa1986/gulp-angular-embed-templates#17]
I noticed a problem with `<img src="/image.png" />` tags only. When compiling Angular2 typescript, the embed templates plugin you've created strips the quotations from the src attribute, this is the point in which quotations are stripped. I then compile the ts into js, so I can test my code. Once loaded, chrome browser loads the img tag as plain text, and not an html element. When I go into the compiled js and add quotations around the attribute value, the image displays correctly.

**Comment by mwehr** [comment]
Hi,

I think this is the minimizer.
Try to set  "quotes: true" in the minimizer options.
```bash
.pipe(embedTemplates({
    sourceType:'ts',
    minimize:{
          quotes: true,
    }
}))
```

regards,

Mario

**Comment by skliffmueller** [comment]
Yep, that did the trick thanks!
