### ISSUE TITLE
Templates should be embedded with new ES6's " ` " character rather than " ' " character.

### ISSUE THREAD

**Issue by vineetshopo** [laxa1986/gulp-angular-embed-templates#18]
If new template syntax of ES6 is implemented then it will give developers better option to use both ' and " characters in their html.

**Comment by martinsik** [comment]
If you're targeting todays browser you can use ES6 **`** quotes. See my answer in #19

**Comment by laxa1986** [comment]
Hello guys. What's the issue? Plugin support all quote types: ' " and `
