### ISSUE TITLE
unpredictable behaviour with angular2

### ISSUE THREAD

**Issue by vineetshopo** [laxa1986/gulp-angular-embed-templates#19]
This gulp plugin sometimes removes " character and sometimes keep this character.

**Comment by martinsik** [comment]
I think you need to provide more information, ideally show some replicable code.

This plugin however uses HTML minimizer called [`minimize`](https://github.com/Swaagie/minimize) where you can set various settings, so if you're having trubles with quotes try forcing it to keep all quotes like (actualy think I was having exactly the same issue):

    .pipe(embedTemplates({
        basePath: 'src/app',
        minimize: {
            quotes: true,
            empty: true
        }
    }))

**Comment by laxa1986** [comment]
I close the issue because author haven't provided any valuable examples. And also because it seems that it was addressed by 'martinsik' comment
