### ISSUE TITLE
Allow for jade, etc templates in addition to HTML

### ISSUE THREAD

**Issue by jrgleason** [laxa1986/gulp-angular-embed-templates#20]
I am using your plugin for html and it works great. Now I would like to seamlessly integrate my jade templates as well, is there a way to do this? I don't see any documentation so right now I am thinking I will need to create a sync task before that will covert all jade into html. 

Any ideas?

**Comment by jrgleason** [comment]
Currently I am just using the gulp-jade plugin to compile them to HTML before but it would be nice to skip that disk write.

**Comment by laxa1986** [comment]
Hello. I'm not sure why you talking about 'disk write'. Just checked my plugin code - it gets data from file.contents so you can use just a chain of plugins working in memory. Does gulp-jade unconditionally write on disk?
