### ISSUE TITLE
Breaking angular2 href

### ISSUE THREAD

**Issue by talmog** [laxa1986/gulp-angular-embed-templates#22]
Hi and thank you for the plugin.

I have an issue with angular2 templates:
this code:
`<a href="http://{{website.value}}" target="_blank">{{website.value}}</a>`

becomes 
`<a href=http://{{website.value}} target=_blank>{{website.value}}</a>`
(quotes are being removed)

and throws a template parsing error:

`boot.js:20 EXCEPTION: Error: Uncaught (in promise): Template parse errors:
Unexpected closing tag "a" ("<a href=http://{{website.value}} target=_blank>{{website.value}}[ERROR ->]</a>`

I am first converting the .ts to .js and then run your plugin on the .js file.

any advice?
Thanks,
Tomer

**Comment by Arkangelg26** [comment]
i have the same issue

**Comment by talmog** [comment]
So that solve the quote problem, but now I get a template error where is it not recognizing some input to components:
`bundle-1519e29096.js:18 Unhandled Promise rejection: Template parse errors:
Can't bind to 'hideEdit' since it isn't a known native property ("rofile($event)">
          <avatar [person] = "node.person" [isCurrentUser] = "isCurrentUser(node)" **[ERROR ->]**[hideEdit] = "node.isNew || node.isIntermediate"></avatar>
        </div>`

**Comment by Arkangelg26** [comment]
Can you give more information? the template before and after run the plugin

**Comment by laxa1986** [comment]
Turned quotes: true by default in v2.3.0
Regarding you issue please attach more details
