### ISSUE TITLE
minimize quotes required on <img>

### ISSUE THREAD

**Issue by martijnkorteweg** [laxa1986/gulp-angular-embed-templates#23]
``` html
<img src="/images/foobar.jpg">
```

turns into

``` html
<img src=/images/foobar.jpg>
```

I have tested Chrome/Safari/Firefox, where the image just shows up as a text line

Settings {minimize: {quotes: true}} solves the problem but seems that should not be required

**Comment by laxa1986** [comment]
Hello. What I can do is to set quotes: true by default, but it will impact all other users who are OK with <img src=/images/foobar.jpg>
What you suggest? and what's the issue with src w/o quotes? I just checked if you put whitespace in the path, then htmlminimizer will keep quotes, so you can be sure that it works just fine

**Comment by cpamp21** [comment]
This causes an application to fail to load when an image is nested within an anchor tag.

> (SystemJS) Template parse errors: Unexpected closing tag "a"

**Comment by cpamp21** [comment]
Quotes true should be default in my opinion. As soon as you have a forward slash in the template that isn't quoted the entire template breaks and fails to load. I was scratching my head for a few hours today trying to figure this out.

**Comment by laxa1986** [comment]
OK then. I changed appearance: now quotes put by default in last version.
