### ISSUE TITLE
Component Inline problem 

### ISSUE THREAD

**Issue by msahamed** [laxa1986/gulp-angular-embed-templates#26]
Recently i faced a problem inlining components. 

If I import a template  in a component like :
               templateUrl :"../app.component.html"

and the app.component.html contains some html with other components : 

<header-component>

<p>
  Hello {{ world }}
</p>

<footer-componet>

I was expecting the "gulp-inline-ng2-template" also import  htmls of <header-component> and <footer-componet> and inline them in app.component.html. However  "gulp-inline-ng2-template" does not. I was wondering if you guys have any solution for this problem.

**Comment by laxa1986** [comment]
Hello. Currently such feature not supported
