### ISSUE TITLE
Minimizer DOM options

### ISSUE THREAD

**Issue by aslubsky** [laxa1986/gulp-angular-embed-templates#27]
I need to use "lowerCaseTags" option. I've set
```
minimize: {
	quotes: true,
	empty: true,
	dom: {
		lowerCaseTags: false,
		lowerCaseAttributeNames: false
	}
}
```
but plugin don't read it. Found in code
```
new html.DomHandler(this.minimizer.emits('read')), {lowerCaseAttributeNames:false}
```

**Comment by joakim-nordicfactory** [comment]
I have the same issue, all my html tags gets transformed to lower case and that screws up my angular2 components, because all of them use camel case selectors. Any fix on this?

**Comment by aslubsky** [comment]
Fix already merged. Wait for release or use master branch in package.json like this:
"gulp-angular-embed-templates": "git+https://github.com/laxa1986/gulp-angular-embed-templates.git"

**Comment by msklausen** [comment]
I have the same issue as joakim-nordicfactory. I'm using PrimeNg which selectors are camelCase. Are there any news of an upcoming release?

**Comment by laxa1986** [comment]
Thanks for such bug fix. Closing this topic
