### ISSUE TITLE
how to embed  in angular 1.5 component

### ISSUE THREAD

**Issue by wesleyqueiroz** [laxa1986/gulp-angular-embed-templates#29]
Hi, 
I tried to generate the template, but nothing happens.
I have something like:

  const app =   angular.module("myWebComponents");
  app.component("myComponent",{    
      templateUrl:'path/to/template/myTemplate.html' ,
       .  .  . 

I'm using component of angular 1.5v

**Comment by alirezamirian** [comment]
It works for `component`s too. Actually code has no idea about `directive`, `component`, `state`, ...
It seems it will manipulate any object with `templateUrl` property. 
Make sure to use relative urls.
It would be nice if specifying **base** was also possible.

**Comment by laxa1986** [comment]
basePath option available
