### ISSUE TITLE
enhancement - templateUrl to be relative to webserver root

### ISSUE THREAD

**Issue by NithinBiliya** [laxa1986/gulp-angular-embed-templates#32]
Scenario -
Using gulp-angular-embed-templates only in production build. So after running gulp task for development build, and testing it, need to rewrite the directive js files to make the template URL relative to the js, and then run the gulp task for production build.

Manual editing of template URL for production build can be avoided by making the plugin pick the URL relative to the webserver root.

**Comment by laxa1986** [comment]
Hello. You're trying to make it too smart :) Actually the task to switch modes should be somewhere higher, somewhere who invoke the plugin.
