### ISSUE TITLE
TemplateUrl Path issues

### ISSUE THREAD

**Issue by MCKRUZ** [laxa1986/gulp-angular-embed-templates#4]
Given I have the following file structure

app 
   - main
      - components
         - directive.js
      - templates
         - template.html

and my directive code looks like this

 var directive = {
            link: link,
            restrict: 'EA',
            templateUrl: 'app/main/templates/foo.html'
        };

How do I get this to work?

When run the function in gulp I get a "can't read template file" because it's trying to put the path of app/main/components before the app/main/templates path.

Even if I put in basePath: '' as a parameter it still fails.

Thoughts?

**Comment by laxa1986** [comment]
Hello MCKRUZ

Just checked how we use this plugin on our project he-he :)

By default it use relative paths: specify relative path to template.
1) remove basePath parameter
2) specify templateUrl: './../templates/you-template.html'

Merry Christmas!

2016-01-05 21:22 GMT+02:00 MCKRUZ <notifications@github.com>:

> Given I have the following file structure
>
> app
>
>    - main
>       - components
>          - directivejs
>       - templates
>          - templatehtml
>
> and my directive code looks like this
>
> var directive = {
> link: link,
> restrict: 'EA',
> templateUrl: 'app/main/templates/foohtml'
> };
>
> How do I get this to work?
>
> When run the function in gulp I get a "can't read template file" because
> it's trying to put the path of app/main/components before the
> app/main/templates path
>
> Even if I put in basePath: '' as a parameter it still fails
>
> Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laxa1986/gulp-angular-embed-templates/issues/4>.
>



-- 
Чекулаев Алексей
