### ISSUE TITLE
How config for angular2

### ISSUE THREAD

**Issue by nukuuk** [laxa1986/gulp-angular-embed-templates#7]
Hello, i am getting the following error using  your plugin:

Can't bind to 'ngif' since it isn't a known native property (" col-md-4" style="padding-top: 15px; text-align: left;"><div class="HeaderStyle1">WELCOME</div><div [ERROR ->]*ngif="!isExpandedWelcomeText">some text some text"): PageMainComponent@0:502
Property binding ngif not used by any directive on an embedded template ("-sm-6 col-md-4" style="padding-top: 15px; text-align: left;"><div class="HeaderStyle1">WELCOME</div>[ERROR ->]<div *ngif="!isExpandedWelcomeText">some text here "): PageMainComponent@0:497

Can you show the proper config for use in angular2?  Many thanks.

Brendan

**Comment by jpf200124** [comment]
Hi nukuuk. 

This issue was fixed in the latest 1.1.0 update. If you are using 1.0.0 you need to update.

**Comment by nukuuk** [comment]
Yup that was the problem.  Many thanks!  Great plugin.

**Comment by laxa1986** [comment]
Hello. It is my first open source project and I really happy that somebody need it and like it.
Please don't hesitate to write about any issues in future.
Soon I will release version 2.0.0 with extended typescript support

**Comment by nukuuk** [comment]
Hi, I plugged your plugin on stackoverflow:  http://stackoverflow.com/a/34781010/3532945

You may want to consider merging your project with gulp-angular2-embed-sass
